/**
 * This code was generated by Builder.io.
 */
import './OrgLandingPage.css';
import React from "react";
import { LoadAndRenderHTML } from "./util";
import Navbar from './Navbar';
import Footer from './Footer';

function OrgLandingPage() {
  var orgName = window.location.pathname.split('/').pop();
  LoadAndRenderHTML('/orgTemplate?orgName=' + orgName, 'org-landing-page', '/admin/assets?orgName=' + orgName);

  return (
    <>
      <div className="div">
        <Navbar />
        <div id='org-landing-page'></div>
        <Footer />
      </div>
    </>
  );
}

export default OrgLandingPage;
